upstream hemasight_api {
  zone hemasight_api 64k;
  resolver 127.0.0.11 valid=5s ipv6=off;
  server api:8000 resolve;
}

server {
  listen 80;
  root /usr/share/nginx/html;
  index index.html;
  location /api/ {
    proxy_pass http://hemasight_api/;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }
  location / { try_files $uri $uri/ /index.html; }
}
